# Generated by Django 3.2.8 on 2021-10-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_member_sondage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='votre_nom',
            field=models.CharField(default='', max_length=255),
        ),
    ]
