# Generated by Django 3.2.8 on 2021-10-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_sondage_votre_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='votant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.member'),
        ),
    ]
