# Generated by Django 3.2.8 on 2021-10-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_alter_sondage_votant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sondage',
            old_name='votant',
            new_name='vote',
        ),
    ]
