# Generated by Django 3.2.8 on 2021-10-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_rename_votant_sondage_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Votre_nom',
            new_name='nom_de_candidat',
        ),
        migrations.RenameField(
            model_name='sondage',
            old_name='vote',
            new_name='candidats',
        ),
    ]
